project:
  type: website
  output-dir: docs
  render:
    - "*.md"
    - "*.md"

website:
  title: "R-multiverse"
  description: "A community-curated package repository system, powered by R-universe"
  site-url: "https://r-multiverse.org"
  favicon: "logo/logo-hexbin.png"
  image: "logo/logo-hexbin.png"
  open-graph: true
  navbar:
    logo: "logo/logo-hexbin.png"
    logo-alt: "R-multiverse"
    left:
    - text: "About"
      menu:
        - text: Community repository
          url: community.md
        - text: Production repository
          url: production.md
    - users.md
    - contributors.md
    - team.md
    - text: "Policies"
      menu:
        - terms.md
        - review.md
        - conduct.md
        - text: Governance Document
          url: governance.md
        - security.md
    tools:
      - icon: github
        aria-label: "GitHub"
        menu:
          - text: Contribute
            url: https://github.com/r-multiverse/contributions
          - text: Report Issue
            url: https://github.com/r-multiverse/help
      - icon: rocket-takeoff
        aria-label: "R-multiverse Community Universe"
        href: https://community.r-multiverse.org
  page-footer:
    left: "&copy; 2024 the R-multiverse project."
    right: "<a href='https://r-consortium.org' style='text-decoration:none'>Supported by the R Consortium</a>."

format:
  html:
    theme: cosmo
    toc: true
