project:
  type: website
  output-dir: docs
  render:
    - "*.md"
    - "*.qmd"

website:
  title: "R-multiverse"
  description: "A community-curated dual R package repository, powered by R-universe"
  site-url: "https://r-multiverse.org"
  favicon: "logo/logo-hexbin.png"
  image: "logo/logo-hexbin.png"
  open-graph: true
  navbar:
    logo: "logo/logo-hexbin.png"
    logo-alt: "R-multiverse"
    left:
    - overview.qmd
    - text: "Repositories"
      menu:
        - text: Community
          url: community.md
        - text: Production
          url: production.qmd
    - contributors.md
    - moderators.md
    - team.md
    - policies.md
    tools:
      - icon: github
        aria-label: "GitHub"
        menu:
          - text: Contribute
            url: https://github.com/r-multiverse/contributions
          - text: Report Issue
            url: https://github.com/r-multiverse/help
      - icon: rocket-takeoff
        aria-label: "R-multiverse Community Universe"
        href: https://community.r-multiverse.org
  page-footer:
    left: "&copy; 2025 the R-multiverse project."
    right: "<a href='https://r-consortium.org' style='text-decoration:none'>Supported by the R Consortium</a>."

format:
  html:
    theme: cosmo
    toc: true
